name: check-lint
on: [push]
jobs:
  black-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Action Lint
        uses: panda0603/lint-action@1.6.3
        with:
          github_token: ${{ secrets.github_token }}
          black: true
